try to get codeowner

diff --git a/.github/workflows/security.yml b/.github/workflows/security.yml
--- a/.github/workflows/security.yml
+++ b/.github/workflows/security.yml
@@ -25,20 +25,28 @@ jobs:
         #   echo "$OWNER_NAME"
         #   echo "$REPO_NAME"
         run: |
-          PATH_TO_CHECK="/.github"
-          OWNER=$(grep "^$PATH_TO_CHECK" CODEOWNERS | awk '{print $2}')
-          echo "OWNER=$OWNER" >> $GITHUB_ENV
-          echo "$OWNER"
+          PATH_TO_CHECK="/.github"  # Especifique o caminho que deseja verificar
+          CODEOWNERS_FILE=".github/CODEOWNERS"  # Caminho para o arquivo CODEOWNERS
+          
+          # Verifica se o arquivo CODEOWNERS existe
+          if [ -f "$CODEOWNERS_FILE" ]; then
+            OWNER=$(grep "^$PATH_TO_CHECK" "$CODEOWNERS_FILE" | awk '{print $2}')
+            echo "OWNER=$OWNER" >> $GITHUB_ENV
+            echo "The owner for $PATH_TO_CHECK is: $OWNER"
+          else
+            echo "CODEOWNERS file not found in $CODEOWNERS_FILE."
+            exit 1
+          fi
 
-      - name: run semgrep
-        run: |
-          semgrep --config="p/default" --json --output=semgrep-report.json
+      # - name: run semgrep
+      #   run: |
+      #     semgrep --config="p/default" --json --output=semgrep-report.json
 
-      - name: save report as pipeline artifact
-        uses: actions/upload-artifact@v3
-        with:
-          name: semgrep-report
-          path: semgrep-report.json
+      # - name: save report as pipeline artifact
+      #   uses: actions/upload-artifact@v3
+      #   with:
+      #     name: semgrep-report
+      #     path: semgrep-report.json
 
   run_iac_scan:
     runs-on: ubuntu-20.04
